FROM golang:1.17-alpine

WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download

ENV VERSION=localdev

COPY . .

WORKDIR hrm

RUN go build -ldflags="-w -s -X main.version=$VERSION" -o hrm && \
	if [ ! -f env/config ]; then cp env/sample.config env/config ; fi

CMD ["sh", "-c", "./hrm"]
