# use buildkit
# export COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1
version: '3'

services:
  postgresd:
    container_name: webex_postgresd
    image: postgres:10.13
    ports:
      - "5432:5432"
    volumes:
      - ./create-webex-database.sh:/docker-entrypoint-initdb.d/create-webex-database.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    restart: unless-stopped

  webex-hrm:
    container_name: webex_hrm
    depends_on:
      - postgresd
    build:
      context: ../..
      dockerfile: deploy/compose/Dockerfile.hrm
    ports:
      - 4000:4000
    environment:
      RUNTIME_ENVIRONMENT: 'development'
      SERVER_PORT: '4000'
      RUNTIME_LOGLEVEL: 'debug'
      DATABASE_HOST: webex_postgresd
      DATABASE_PORT: "5432"
      DATABASE_USER: postgres
      DATABASE_DBNAME: hrmdb
      DATABASE_PASSWORD: secret
    restart: unless-stopped

  webex-cms:
    container_name: webex_cms
    depends_on:
      - webex-hrm
    build:
      context: ../..
      dockerfile: deploy/compose/Dockerfile.cms
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      RUNTIME_ENVIRONMENT: 'development'
      HOST: localhost
      PORT: '3000'
      HRM_URL: 'webex-hrm:4000'
      CSRF_SECRET: somethingsecret
    restart: unless-stopped
    volumes:
      - ../../cms/assets:/src/cms/assets
